export const REGISTRO_CORRECTO = "REGISTRO_CORRECTO";
export const REGISTRO_INCORRECTO = "REGISTRO_INCORRECTO";

export const LOGIN_CORRECTO = "LOGIN_CORRECTO";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const CERRAR_SESION = "CERRAR_SESION";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const LIMPIAR_ALERTA = "LIMPIAR_ALERTA";

export const SUBIR_ARCHIVO = "SUBIR_ARCHIVO";
export const SUBIR_ARCHIVO_CORRECTO = "SUBIR_ARCHIVO_CORRECTO";
export const SUBIR_ARCHIVO_ERROR = "SUBIR_ARCHIVO_ERROR";

export const CREAR_ENLACE_CORRECTO = "CREAR_ENLACE_CORRECTO";
export const CREAR_ENLACE_ERROR = "CREAR_ENLACE_ERROR";

export const LIMPIAR_STATE = "LIMPIAR_STATE";

export const AGREGAR_PASSWORD = "AGREGAR_PASSWORD";
export const NUMERO_DESCARGAS = "NUMERO_DESCARGAS";